"""
Brand Locations Enrichment Script
==================================
1. Adds a large curated list of ~800 brands across key Amazon UK categories.
2. Optionally scrapes the first page of Amazon UK search results for specified
   category keywords and extracts brand names, then attempts to assign origin.

Usage:
    python enrich_brand_locations.py          # static list only
    python enrich_brand_locations.py --scrape  # static list + live scrape

The script is idempotent — it never overwrites an existing entry.
"""

import json
import re
import sys
import time
import os
import random

BRAND_JSON_PATH = os.path.join(
    os.path.dirname(__file__), '..', '..', 'common', 'data', 'json', 'brand_locations.json'
)

# ---------------------------------------------------------------------------
# CURATED BRAND LIST
# Keys are lowercase brand names as used by resolve_brand_origin().
# Country = manufacturing / design origin most relevant for CO₂ estimation.
# ---------------------------------------------------------------------------

CURATED_BRANDS = {
    # ── Furniture / Tables ─────────────────────────────────────────────────
    'multigot':            'China',
    'homcom':              'China',
    'costway':             'China',
    'yaheetech':           'China',
    'songmics':            'China',
    'vasagle':             'China',
    'homfa':               'China',
    'sobuy':               'China',
    'tectake':             'China',
    'vonhaus':             'China',
    'furniturebox':        'UK',
    'living and home':     'China',
    'walker edison':       'China',
    'sauder':              'USA',
    'zinus':               'China',
    'ashley':              'China',
    'dorel':               'Canada',
    'teamson':             'China',
    'novosolo':            'Denmark',
    'dhp':                 'China',
    'keter':               'Israel',
    'lifetime':            'China',
    'better homes & gardens': 'China',
    'we furniture':        'China',
    'tvilum':              'Denmark',
    'birlea':              'China',
    'argos home':          'China',
    'julian bowen':        'China',
    'seconique':           'China',
    'vida designs':        'China',
    'lloyd pascal':        'China',
    'dams':                'UK',
    'teknik':              'China',
    'alphason':            'China',
    'afc':                 'China',
    'harrier sport':       'China',
    'homestyle4u':         'China',
    'flair furniture':     'China',
    'habitat':             'China',
    'heal\'s':             'UK',
    'heal':                'UK',
    'made.com':            'China',
    'made':                'China',
    'dunelm':              'China',
    'next home':           'China',
    'oak furnitureland':   'China',
    'dwell':               'China',

    # ── Knives / Cutlery ───────────────────────────────────────────────────
    'victorinox':          'Switzerland',
    'wüsthof':             'Germany',
    'wusthof':             'Germany',
    'zwilling':            'Germany',
    'j.a. henckels':       'Germany',
    'henckels':            'Germany',
    'global knives':       'Japan',
    'global':              'Japan',
    'mac knife':           'Japan',
    'mac':                 'Japan',
    'kai':                 'Japan',
    'shun':                'Japan',
    'miyabi':              'Germany',
    'messermeister':       'Germany',
    'mercer culinary':     'China',
    'mercer':              'China',
    'dexter-russell':      'USA',
    'f. dick':             'Germany',
    'opinel':              'France',
    'sabatier':            'France',
    'sabatier professional': 'France',
    'ka-bar':              'USA',
    'buck knives':         'USA',
    'gerber':              'USA',
    'benchmade':           'USA',
    'spyderco':            'USA',
    'kershaw':             'Japan',
    'crkt':                'China',
    'ontario':             'USA',
    'mora':                'Sweden',
    'morakniv':            'Sweden',
    'fiskars':             'Finland',
    'tramontina':          'Brazil',
    'scanpan':             'Denmark',
    'cangshan':            'China',
    'dalstrong':           'China',
    'zelite infinity':     'China',
    'misen':               'China',
    'babish':              'China',
    'seki edge':           'Japan',
    'richardson sheffield': 'UK',
    'prestige':            'China',
    'stellar':             'UK',
    'tower':               'China',
    'raymond blanc':       'France',

    # ── Lighting ───────────────────────────────────────────────────────────
    'philips hue':         'Netherlands',
    'lifx':                'Australia',
    'govee':               'China',
    'wiz':                 'Belgium',
    'tp-link':             'China',
    'tapo':                'China',
    'nanoleaf':            'Canada',
    'sengled':             'China',
    'elgato':              'Germany',
    'cree lighting':       'USA',
    'ge lighting':         'USA',
    'osram':               'Germany',
    'lutron':              'USA',
    'leviton':             'USA',
    'ring':                'USA',
    'eve systems':         'Germany',
    'hue':                 'Netherlands',
    'yeelight':            'China',
    'kasa':                'China',
    'meross':              'China',
    'treatlife':           'China',
    'lohas':               'China',
    'lepro':               'China',
    'lumary':              'China',
    'ledvance':            'Germany',
    'sylvania':            'Germany',
    'energizer':           'USA',
    'auraglow':            'UK',
    'bayco':               'USA',
    'livarno':             'Germany',
    'brilliant smart':     'Australia',
    'lexi lighting':       'UK',
    'nordlux':             'Denmark',
    'astro lighting':      'UK',
    'dar lighting':        'UK',
    'endon':               'UK',
    'saxby':               'UK',
    'lucide':              'Belgium',
    'trio leuchten':       'Germany',
    'paulmann':            'Germany',
    'eglo':                'Austria',
    'searchlight':         'UK',
    'firstlight':          'UK',

    # ── Bottles / Drinkware ────────────────────────────────────────────────
    'hydro flask':         'USA',
    'nalgene':             'USA',
    'yeti':                'USA',
    'camelbak':            'USA',
    'klean kanteen':       'USA',
    's\'well':             'USA',
    'swell':               'USA',
    'lifestraw':           'Switzerland',
    "chilly's":            'UK',
    'chillys':             'UK',
    'thermos':             'USA',
    'stanley':             'USA',
    'zojirushi':           'Japan',
    'tiger':               'Japan',
    'contigo':             'USA',
    'takeya':              'USA',
    'simple modern':       'USA',
    'blenderbottle':       'USA',
    'embrava':             'USA',
    'iron flask':          'China',
    'mira':                'USA',
    'reduce':              'USA',
    'ello':                'USA',
    'manna':               'UK',
    'avex':                'USA',
    'ozark trail':         'China',
    'greens steel':        'China',
    'elemental':           'USA',
    'peak':                'China',
    'bobble':              'USA',
    'built ny':            'China',
    'built':               'China',
    'joyjolt':             'China',
    'glasstic':            'China',
    'bkr':                 'USA',
    'memobottle':          'Australia',
    'soma':                'USA',
    'brita':               'Germany',
    'bobble':              'USA',

    # ── Kettles / Small Appliances ─────────────────────────────────────────
    'breville':            'Australia',
    'de\'longhi':          'Italy',
    'delonghi':            'Italy',
    'kitchenaid':          'USA',
    'russell hobbs':       'China',
    'morphy richards':     'China',
    'dualit':              'UK',
    'smeg':                'Italy',
    'balmuda':             'Japan',
    'kenwood':             'China',
    'cuisinart':           'China',
    'ninja':               'China',
    'hamilton beach':      'China',
    'instant pot':         'China',
    'instant':             'China',
    'sage':                'Australia',
    'tefal':               'France',
    'rowenta':             'France',
    'moulinex':            'France',
    'electrolux':          'Sweden',
    'bosch':               'Germany',
    'siemens':             'Germany',
    'miele':               'Germany',
    'aeg':                 'Sweden',
    'neff':                'Germany',
    'philips':             'Netherlands',
    'nespresso':           'Switzerland',
    'krups':               'Germany',
    'melitta':             'Germany',
    'jura':                'Switzerland',
    'gaggia':              'Italy',
    'la marzocco':         'Italy',
    'rancilio':            'Italy',
    'rocket espresso':     'Italy',
    'nutramilk':           'UK',
    'vitamix':             'USA',
    'blendjet':            'China',
    'nutribullet':         'USA',
    'magimix':             'France',
    'food network':        'China',
    'tower':               'China',
    'quest':               'China',
    'daewoo':              'South Korea',
    'nikai':               'UAE',

    # ── Watches ────────────────────────────────────────────────────────────
    'rolex':               'Switzerland',
    'seiko':               'Japan',
    'citizen':             'Japan',
    'casio':               'Japan',
    'fossil':              'China',
    'timex':               'China',
    'garmin':              'Taiwan',
    'tag heuer':           'Switzerland',
    'omega':               'Switzerland',
    'breitling':           'Switzerland',
    'longines':            'Switzerland',
    'tissot':              'Switzerland',
    'hamilton':            'Switzerland',
    'swatch':              'Switzerland',
    'movado':              'China',
    'bulova':              'Japan',
    'invicta':             'China',
    'orient':              'Japan',
    'skagen':              'China',
    'daniel wellington':   'China',
    'mvmt':                'China',
    'nixon':               'China',
    'ice-watch':           'Belgium',
    'sekonda':             'China',
    'accurist':            'China',
    'adidas':              'Germany',
    'emporio armani':      'Italy',
    'michael kors':        'China',
    'guess':               'China',
    'armani exchange':     'Italy',
    'vivienne westwood':   'China',
    'hugo boss':           'Germany',
    'tommy hilfiger':      'China',
    'calvin klein':        'China',
    'dkny':                'China',
    'kate spade':          'China',
    'coach':               'China',
    'marc jacobs':         'China',
    'versace':             'Italy',
    'diesel':              'Italy',
    'gc':                  'Switzerland',
    'festina':             'Spain',
    'lotus':               'Spain',
    'lorus':               'Japan',
    'pulsar':              'Japan',
    'tw steel':            'Netherlands',
    'police':              'China',
    'esprit':              'Germany',
    'komono':              'Belgium',
    'cluse':               'Netherlands',
    'triwa':               'Sweden',
    'withings':            'France',
    'suunto':              'Finland',
    'polar':               'Finland',
    'fitbit':              'USA',
    'apple':               'China',
    'samsung':             'South Korea',
    'huawei':              'China',
    'xiaomi':              'China',
    'amazfit':             'China',
    'ticwatch':            'China',
    'mobvoi':              'China',
    'fossil':              'China',

    # ── Electronics / Tech ─────────────────────────────────────────────────
    'sony':                'Japan',
    'lg':                  'South Korea',
    'panasonic':           'Japan',
    'sharp':               'Japan',
    'toshiba':             'Japan',
    'hitachi':             'Japan',
    'jvc':                 'Japan',
    'pioneer':             'Japan',
    'denon':               'Japan',
    'marantz':             'Japan',
    'yamaha':              'Japan',
    'bose':                'USA',
    'harman kardon':       'USA',
    'jbl':                 'USA',
    'skullcandy':          'USA',
    'sennheiser':          'Germany',
    'beyerdynamic':        'Germany',
    'akg':                 'Austria',
    'audio-technica':      'Japan',
    'shure':               'USA',
    'plantronics':         'USA',
    'jabra':               'Denmark',
    'logitech':            'Switzerland',
    'razer':               'Singapore',
    'corsair':             'USA',
    'steelseries':         'Denmark',
    'hyperx':              'USA',
    'roccat':              'Germany',
    'trust':               'Netherlands',
    'anker':               'China',
    'aukey':               'China',
    'ravpower':            'China',
    'baseus':              'China',
    'ugreen':              'China',
    'orico':               'China',
    'inateck':             'China',
    'sabrent':             'USA',
    'seagate':             'USA',
    'western digital':     'USA',
    'wd':                  'USA',
    'sandisk':             'USA',
    'kingston':            'USA',
    'samsung electronics': 'South Korea',
    'crucial':             'USA',
    'corsair':             'USA',
    'intel':               'USA',
    'amd':                 'USA',
    'nvidia':              'USA',
    'asus':                'Taiwan',
    'msi':                 'Taiwan',
    'gigabyte':            'Taiwan',
    'acer':                'Taiwan',
    'lenovo':              'China',
    'dell':                'USA',
    'hp':                  'USA',
    'microsoft':           'USA',
    'amazon':              'USA',
    'google':              'USA',
    'roku':                'USA',

    # ── Home Appliances ────────────────────────────────────────────────────
    'dyson':               'UK',
    'hoover':              'USA',
    'bissell':             'USA',
    'shark':               'China',
    'irobot':              'USA',
    'roomba':              'USA',
    'karcher':             'Germany',
    'nilfisk':             'Denmark',
    'vax':                 'UK',
    'henry':               'UK',
    'numatic':             'UK',
    'miele':               'Germany',
    'bosch':               'Germany',
    'siemens':             'Germany',
    'hotpoint':            'Italy',
    'indesit':             'Italy',
    'whirlpool':           'USA',
    'maytag':              'USA',
    'kitchenaid':          'USA',
    'smeg':                'Italy',
    'rangemaster':         'UK',
    'aga':                 'UK',
    'falcon':              'UK',
    'beko':                'Turkey',
    'hisense':             'China',
    'haier':               'China',
    'lg':                  'South Korea',
    'samsung':             'South Korea',
    'candy':               'Italy',
    'hopoint':             'Italy',
    'zanussi':             'Sweden',

    # ── Health & Beauty ────────────────────────────────────────────────────
    'philips sonicare':    'Netherlands',
    'oral-b':              'Germany',
    'braun':               'Germany',
    'panasonic':           'Japan',
    'remington':           'UK',
    'wahl':                'USA',
    'andis':               'USA',
    'babyliss':            'France',
    'ghd':                 'UK',
    'cloud nine':          'UK',
    'tigi':                'USA',
    'l\'oreal':            'France',
    'loreal':              'France',
    'garnier':             'France',
    'maybelline':          'USA',
    'revlon':              'USA',
    'mac cosmetics':       'USA',
    'charlotte tilbury':   'UK',
    'nars':                'USA',
    'urban decay':         'USA',
    'too faced':           'USA',
    'anastasia beverly hills': 'USA',
    'morphe':              'USA',
    'fenty beauty':        'USA',
    'kylie cosmetics':     'USA',
    'olaplex':             'USA',
    'kerastase':           'France',
    'wella':               'Germany',
    'schwarzkopf':         'Germany',
    'redken':              'USA',
    'paul mitchell':       'USA',
    'tresemme':            'USA',
    'dove':                'Netherlands',
    'nivea':               'Germany',
    'neutrogena':          'USA',
    'cerave':              'USA',
    'la roche-posay':      'France',
    'vichy':               'France',
    'the ordinary':        'Canada',
    'drunk elephant':      'USA',
    'tatcha':              'Japan',
    'lush':                'UK',
    'elemis':              'UK',

    # ── Sports & Outdoors ──────────────────────────────────────────────────
    'nike':                'China',
    'adidas':              'Germany',
    'puma':                'Germany',
    'reebok':              'China',
    'asics':               'Japan',
    'new balance':         'China',
    'under armour':        'China',
    'columbia':            'USA',
    'north face':          'China',
    'patagonia':           'USA',
    'arc\'teryx':          'Canada',
    'arcteryx':            'Canada',
    'the north face':      'China',
    'salomon':             'France',
    'merrell':             'China',
    'keen':                'China',
    'timberland':          'China',
    'hi-tec':              'UK',
    'regatta':             'China',
    'berghaus':            'China',
    'helly hansen':        'Norway',
    'mammut':              'Switzerland',
    'black diamond':       'USA',
    'petzl':               'France',
    'camp':                'Italy',
    'msr':                 'USA',
    'primus':              'Sweden',
    'jetboil':             'USA',
    'nemo':                'USA',
    'big agnes':           'USA',
    'therm-a-rest':        'USA',
    'exped':               'Switzerland',
    'lifesystems':         'UK',
    'cotswold outdoor':    'UK',
    'go outdoors':         'UK',
    'trespass':            'UK',

    # ── Books & Stationery ─────────────────────────────────────────────────
    'stabilo':             'Germany',
    'faber-castell':       'Germany',
    'pilot':               'Japan',
    'uni-ball':            'Japan',
    'mitsubishi pencil':   'Japan',
    'pentel':              'Japan',
    'staedtler':           'Germany',
    'bic':                 'France',
    'sharpie':             'USA',
    'crayola':             'USA',
    'posca':               'Japan',
    'winsor & newton':     'UK',
    'derwent':             'UK',
    'conte':               'France',
    'moleskine':           'Italy',
    'leuchtturm1917':      'Germany',
    'rhodia':              'France',
    'midori':              'Japan',
    'traveler\'s notebook': 'Japan',
    'clairefontaine':      'France',
    'paperblanks':         'Canada',
    'kikkerland':          'USA',
    'typo':                'Australia',

    # ── Toys & Kids ────────────────────────────────────────────────────────
    'lego':                'Denmark',
    'playmobil':           'Germany',
    'fisher-price':        'China',
    'mattel':              'China',
    'hasbro':              'China',
    'vtech':               'China',
    'leapfrog':            'China',
    'orchard toys':        'UK',
    'ravensburger':        'Germany',
    'clementoni':          'Italy',
    'djeco':               'France',
    'haba':                'Germany',
    'steiff':              'Germany',
    'zapf creation':       'Germany',
    'barbie':              'China',
    'hot wheels':          'China',
    'nerf':                'China',
    'funko pop':           'China',
    'funko':               'China',

    # ── Garden & Outdoor ──────────────────────────────────────────────────
    'bosch garden':        'Germany',
    'husqvarna':           'Sweden',
    'honda':               'Japan',
    'dewalt':              'USA',
    'makita':              'Japan',
    'ryobi':               'Japan',
    'stihl':               'Germany',
    'flymo':               'Sweden',
    'alm':                 'UK',
    'fiskars':             'Finland',
    'felco':               'Switzerland',
    'wolf garten':         'Germany',
    'spear & jackson':     'UK',
    'burgon & ball':       'UK',
    'kent & stowe':        'UK',
    'terrain':             'UK',
    'haws':                'UK',
    'whitefurze':          'UK',

    # ── Pet Supplies ───────────────────────────────────────────────────────
    'royal canin':         'France',
    'hills':               'USA',
    'purina':              'USA',
    'iams':                'USA',
    'whiskas':             'USA',
    'felix':               'USA',
    'pedigree':            'USA',
    'cesar':               'USA',
    'lily\'s kitchen':     'UK',
    'forthglade':          'UK',
    'naturo':              'UK',
    'harringtons':         'UK',
    'james wellbeloved':   'UK',
    'burns pet nutrition': 'UK',
    'canagan':             'UK',
    'orijen':              'Canada',
    'acana':               'Canada',
    'taste of the wild':   'USA',
    'blue buffalo':        'USA',
    'wellness':            'USA',

    # ── Clothing & Fashion ─────────────────────────────────────────────────
    'levi\'s':             'USA',
    'levis':               'USA',
    'levi strauss':        'USA',
    'wrangler':            'USA',
    'lee':                 'USA',
    'gap':                 'USA',
    'h&m':                 'Sweden',
    'zara':                'Spain',
    'mango':               'Spain',
    'primark':             'Ireland',
    'marks & spencer':     'UK',
    'm&s':                 'UK',
    'next':                'UK',
    'topshop':             'UK',
    'asos':                'UK',
    'boohoo':              'UK',
    'missguided':          'UK',
    'pretty little thing': 'UK',
    'shein':               'China',
    'uniqlo':              'Japan',
    'muji':                'Japan',
    'cos':                 'Sweden',
    'arket':               'Sweden',
    '& other stories':     'Sweden',
    'monki':               'Sweden',
    'weekday':             'Sweden',
    'ralph lauren':        'USA',
    'polo ralph lauren':   'USA',
    'lacoste':             'France',
    'fred perry':          'UK',
    'burberry':            'UK',
    'barbour':             'UK',
    'hackett':             'UK',
    'gant':                'Sweden',
    'superdry':            'UK',
    'jack & jones':        'Denmark',
    'only':                'Denmark',
    'vero moda':           'Denmark',
    'selected homme':      'Denmark',
    'boss':                'Germany',
    'armani':              'Italy',
    'gucci':               'Italy',
    'prada':               'Italy',
    'fendi':               'Italy',
    'dolce & gabbana':     'Italy',
    'stone island':        'Italy',
    'cp company':          'Italy',
    'moncler':             'France',
    'canada goose':        'Canada',
    'woolrich':            'USA',
    'carhartt':            'USA',
    'dickies':             'USA',
    'lululemon':           'Canada',
    'gymshark':            'UK',
    'sweaty betty':        'UK',
    'ronhill':             'UK',
    'craft sportswear':    'Sweden',
    'odlo':                'Switzerland',
    'protest':             'Netherlands',

    # ── Shoes & Footwear ──────────────────────────────────────────────────
    'clarks':              'UK',
    'dr. martens':         'UK',
    'dr martens':          'UK',
    'ugg':                 'USA',
    'birkenstock':         'Germany',
    'converse':            'China',
    'vans':                'China',
    'skechers':            'China',
    'crocs':               'USA',
    'fitflop':             'UK',
    'ecco':                'Denmark',
    'geox':                'Italy',
    'camper':              'Spain',
    'tod\'s':              'Italy',
    'tods':                'Italy',
    'loake':               'UK',
    'trickers':            'UK',
    'grenson':             'UK',
    'churchs':             'UK',
    'church\'s':           'UK',
    'joseph cheaney':      'UK',
    'hunter':              'UK',
    'aigle':               'France',
    'le chameau':          'France',
    'moon boot':           'Italy',
    'sorel':               'Canada',
    'hoka':                'France',
    'on running':          'Switzerland',
    'on':                  'Switzerland',
    'brooks':              'USA',
    'mizuno':              'Japan',
    'saucony':             'USA',
    'new balance':         'USA',
    'altra':               'USA',
    'inov-8':              'UK',
    'scarpa':              'Italy',
    'la sportiva':         'Italy',
    'five ten':            'USA',

    # ── Bags & Luggage ────────────────────────────────────────────────────
    'samsonite':           'Belgium',
    'american tourister':  'Belgium',
    'antler':              'UK',
    'it luggage':          'UK',
    'eastpak':             'Belgium',
    'herschel':            'Canada',
    'fjallraven':          'Sweden',
    'fjällräven':          'Sweden',
    'osprey':              'USA',
    'deuter':              'Germany',
    'gregory':             'USA',
    'lowe alpine':         'UK',
    'karrimor':            'UK',
    'bergans':             'Norway',
    'tumi':                'USA',
    'briggs & riley':      'USA',
    'rimowa':              'Germany',
    'bric\'s':             'Italy',
    'mandarina duck':      'Italy',
    'longchamp':           'France',
    'mulberry':            'UK',
    'radley':              'UK',
    'accessorize':         'UK',
    'fossil bags':         'China',
    'coach bags':          'China',
    'michael kors bags':   'China',
    'kate spade bags':     'USA',
    'the cambridge satchel company': 'UK',
    'kipling':             'Belgium',
    'pacsafe':             'Australia',
    'baggallini':          'USA',
    'travelon':            'USA',

    # ── Gaming ────────────────────────────────────────────────────────────
    'nintendo':            'Japan',
    'playstation':         'Japan',
    'xbox':                'USA',
    'steam deck':          'USA',
    'valve':               'USA',
    'nacon':               'France',
    'thrustmaster':        'France',
    'hori':                'Japan',
    'pdp':                 'USA',
    'power a':             'China',
    'powera':              'China',
    '8bitdo':              'China',
    'turtle beach':        'USA',
    'astro gaming':        'USA',
    'stealth':             'UK',
    'game':                'UK',
    'konix':               'France',
    'snakebyte':           'Germany',
    'piranha':             'UK',
    'subsonic':            'France',

    # ── Cookware & Kitchen ────────────────────────────────────────────────
    'le creuset':          'France',
    'staub':               'France',
    'lodge':               'USA',
    'cast iron':           'China',
    'circulon':            'USA',
    'anolon':              'USA',
    'meyer':               'USA',
    'all-clad':            'USA',
    'calphalon':           'USA',
    'hexclad':             'USA',
    'caraway':             'USA',
    'greenpan':            'Belgium',
    'tefal ingenio':       'France',
    'kitchen craft':       'UK',
    'judge cookware':      'UK',
    'stellar cookware':    'UK',
    'pendeford':           'UK',
    'pyrex':               'USA',
    'kilner':              'UK',
    'mason cash':          'UK',
    'denby':               'UK',
    'portmeirion':         'UK',
    'royal worcester':     'UK',
    'spode':               'UK',
    'wedgwood':            'UK',
    'royal doulton':       'UK',
    'maxwell & williams':  'Australia',
    'typhoon':             'China',
    'sabichi':             'China',
    'joseph joseph':       'UK',
    'lakeland':            'UK',

    # ── Coffee & Tea ──────────────────────────────────────────────────────
    'nescafe':             'Switzerland',
    'lavazza':             'Italy',
    'illy':                'Italy',
    'pact coffee':         'UK',
    'union hand-roasted':  'UK',
    'hasbean':             'UK',
    'monmouth':            'UK',
    'taylors of harrogate':'UK',
    'clipper':             'UK',
    'teapigs':             'UK',
    'yorkshire tea':       'UK',
    'pg tips':             'Netherlands',
    'tetley':              'India',
    'twinings':            'UK',
    'ahmad tea':           'UK',
    'lipton':              'Netherlands',
    'whittard':            'UK',
    'fortnum & mason':     'UK',
    'aeropress':           'USA',
    'hario':               'Japan',
    'chemex':              'USA',
    'v60':                 'Japan',
    'comandante':          'Germany',

    # ── Baby & Nursery ────────────────────────────────────────────────────
    'bugaboo':             'Netherlands',
    'uppababy':            'USA',
    'icandy':              'UK',
    'silver cross':        'UK',
    'mamas & papas':       'UK',
    'joie':                'China',
    'graco':               'USA',
    'britax':              'Germany',
    'maxi-cosi':           'Netherlands',
    'chicco':              'Italy',
    'stokke':              'Norway',
    'hauck':               'Germany',
    'cosatto':             'UK',
    'bumbleride':          'USA',
    'ergobaby':            'USA',
    'babybjorn':           'Sweden',
    'manduca':             'Germany',
    'cybex':               'Germany',
    'nuna':                'Netherlands',
    'micralite':           'UK',
    'mountain buggy':      'New Zealand',
    'quinny':              'Netherlands',
    'tommee tippee':       'UK',
    'avent':               'Netherlands',
    'dr brown\'s':         'USA',
    'medela':              'Switzerland',
    'lansinoh':            'USA',
    'pampers':             'USA',
    'huggies':             'USA',
    'little ones':         'UK',
    'mama bear':           'China',

    # ── Skincare / Personal Care ───────────────────────────────────────────
    'simple':              'UK',
    'clean & clear':       'USA',
    'clearasil':           'UK',
    'e.l.f.':              'USA',
    'revolution beauty':   'UK',
    'nyx':                 'USA',
    'essence':             'Germany',
    'catrice':             'Germany',
    'rimmel':              'UK',
    'max factor':          'USA',
    'collection':          'UK',
    'seventeen':           'UK',
    'barry m':             'UK',
    'beauty uk':           'UK',
    'soap & glory':        'UK',
    'ted baker':           'UK',
    'sanctuary spa':       'UK',
    'radox':               'Netherlands',
    'imperial leather':    'UK',
    'carex':               'UK',
    'dettol':              'UK',
    'lifebuoy':            'Netherlands',
    'palmolive':           'USA',
    'head & shoulders':    'USA',
    'herbal essences':     'USA',
    'pantene':             'USA',
    'aussie':              'USA',
    'alberto balsam':      'UK',
    'vo5':                 'USA',
    'lynx':                'Netherlands',
    'sure':                'Netherlands',
    'dove deodorant':      'Netherlands',
    'old spice':           'USA',
    'gillette':            'USA',
    'wilkinson sword':     'Germany',
    'schick':              'USA',
    'harry\'s':            'USA',
    'dollar shave club':   'USA',
    'king c. gillette':    'USA',

    # ── Home Decor ────────────────────────────────────────────────────────
    'artiss':              'Australia',
    'umbra':               'Canada',
    'ivar':                'Sweden',
    'ikea':                'Sweden',
    'hay':                 'Denmark',
    'muuto':               'Denmark',
    'normann copenhagen':  'Denmark',
    'ferm living':         'Denmark',
    'menu':                'Denmark',
    'vitra':               'Switzerland',
    'kartell':             'Italy',
    'artemide':            'Italy',
    'flos':                'Italy',
    'driade':              'Italy',
    'magis':               'Italy',
    'knoll':               'USA',
    'herman miller':       'USA',
    'humanscale':          'USA',
    'vitsoe':              'UK',
    'ercol':               'UK',
    'g plan':              'UK',
    'parker knoll':        'UK',
    'barker & stonehouse': 'UK',
    'loaf':                'UK',
    'swoon':               'UK',
    'john lewis':          'UK',
    'bhs':                 'UK',
    'wayfair':             'USA',
    'cox & cox':           'UK',
    'graham & green':      'UK',
    'rockett st george':   'UK',
    'amara':               'UK',
    'nkuku':               'UK',
    'sass & belle':        'UK',
    'rice dk':             'Denmark',
    'bloomingville':       'Denmark',
    'house doctor':        'Denmark',
    'broste copenhagen':   'Denmark',
    'hubsch interior':     'Denmark',

    # ── Tools & DIY ───────────────────────────────────────────────────────
    'stanley tools':       'USA',
    'fatmax':              'USA',
    'irwin':               'USA',
    'bahco':               'Sweden',
    'knipex':              'Germany',
    'wera':                'Germany',
    'snap-on':             'USA',
    'draper':              'UK',
    'faithfull':           'UK',
    'silverline':          'UK',
    'rolson':              'UK',
    'erbauer':             'UK',
    'titan tools':         'UK',
    'magnusson':           'UK',
    'evolution':           'UK',
    'black+decker':        'USA',
    'black & decker':      'USA',
    'milwaukee':           'USA',
    'metabo':              'Germany',
    'festool':             'Germany',
    'hikoki':              'Japan',
    'hitachi tools':       'Japan',
    'einhell':             'Germany',
    'worx':                'USA',
    'ozito':               'Australia',
    'parkside':            'Germany',
    'tacklife':            'China',
    'terratek':            'China',

    # ── Stationery & Office ───────────────────────────────────────────────
    'hp printer':          'USA',
    'epson':               'Japan',
    'canon printer':       'Japan',
    'brother':             'Japan',
    'avery':               'Germany',
    'leitz':               'Germany',
    'esselte':             'Sweden',
    'fellowes':            'USA',
    'rexel':               'UK',
    'acco':                'USA',
    'kensington':          'USA',
    'post-it':             'USA',
    '3m':                  'USA',
    'papermate':           'USA',
    'zebra pen':           'Japan',
    'cross pen':           'USA',
    'parker pen':          'France',
    'lamy':                'Germany',
    'kaweco':              'Germany',
    'twsbi':               'Taiwan',
    'platinum pen':        'Japan',
    'sailor pen':          'Japan',
    'rhodia notepad':      'France',

    # ── Phone Accessories ─────────────────────────────────────────────────
    'spigen':              'South Korea',
    'otterbox':            'USA',
    'casetify':            'USA',
    'lifeproof':           'USA',
    'moshi':               'USA',
    'proporta':            'UK',
    'tech21':              'UK',
    'belkin':              'USA',
    'mophie':              'USA',
    'zagg':                'USA',
    'ringke':              'South Korea',
    'supcase':             'China',
    'itskins':             'France',
    'quad lock':           'Australia',
    'moment':              'USA',
    'peak design':         'USA',
    'nomad':               'USA',
    'decoded':             'Netherlands',

    # ── Smart Home ────────────────────────────────────────────────────────
    'amazon echo':         'USA',
    'alexa':               'USA',
    'nest':                'USA',
    'google home':         'USA',
    'hive':                'UK',
    'tado':                'Germany',
    'netatmo':             'France',
    'myenergi':            'UK',
    'drayton':             'UK',
    'honeywell home':      'USA',
    'wiser':               'France',
    'lightwave':           'UK',
    'innr':                'Netherlands',
    'ikea smart':          'Sweden',
    'tradfri':             'Sweden',
    'shelly':              'Bulgaria',
    'sonos':               'USA',
    'bluesound':           'Canada',
    'naim':                'UK',
    'linn':                'UK',
    'cambridge audio':     'UK',
    'mission':             'UK',
    'wharfedale':          'UK',
    'q acoustics':         'UK',
    'monitor audio':       'UK',
    'bowers & wilkins':    'UK',
    'b&w':                 'UK',
    'meridian':            'UK',
    'arcam':               'UK',
    'rega':                'UK',

    # ── Fitness & Gym ─────────────────────────────────────────────────────
    'bowflex':             'USA',
    'nordic track':        'USA',
    'nordictrack':         'USA',
    'peloton':             'USA',
    'technogym':           'Italy',
    'life fitness':        'USA',
    'precor':              'USA',
    'concept2':            'USA',
    'waterrower':          'USA',
    'kettler':             'Germany',
    'bh fitness':          'Spain',
    'finnlo':              'Germany',
    'hammer strength':     'USA',
    'body solid':          'USA',
    'powertec':            'USA',
    'mirafit':             'UK',
    'bodypower':           'UK',
    'xtreme monkey':       'USA',
    'bulldog equipment':   'UK',
    'york barbell':        'USA',
    'cap barbell':         'USA',
    'primal strength':     'UK',
    'rouge fitness':       'USA',
    'rep fitness':         'USA',
    'eleiko':              'Sweden',
    'rogue':               'USA',
    'again faster':        'UK',
    'wolverson fitness':   'UK',
    'valor fitness':       'USA',
    'bodycraft':           'China',
    'reebok fitness':      'China',
    'domyos':              'France',
    'decathlon':           'France',
    'kipsta':              'France',
    'quechua':             'France',

    # ── Automotive ────────────────────────────────────────────────────────
    'halfords':            'UK',
    'draper automotive':   'UK',
    'sealey':              'UK',
    'laser tools':         'UK',
    'ring automotive':     'UK',
    'nextbase':            'UK',
    'viofo':               'China',
    'garmin dash cam':     'Taiwan',
    'thinkware':           'South Korea',
    'blackvue':            'South Korea',
    'meguiars':            'USA',
    'autoglym':            'UK',
    'gtechniq':            'UK',
    'gyeon':               'South Korea',
    'chemical guys':       'USA',
    'turtle wax':          'USA',
    'car plan':            'UK',
    'comma oil':           'UK',
    'castrol':             'UK',
    'mobil 1':             'USA',
    'shell helix':         'Netherlands',
    'thule':               'Sweden',
    'yakima':              'USA',
    'halfords essentials': 'UK',
    'michelin accessories':'France',
    'slime':               'USA',
    'dynaplug':            'USA',
    'continental tyres':   'Germany',

    # ── Musical Instruments ───────────────────────────────────────────────
    'fender':              'USA',
    'gibson':              'USA',
    'martin guitar':       'USA',
    'taylor guitars':      'USA',
    'guild':               'USA',
    'epiphone':            'China',
    'ibanez':              'Japan',
    'esp':                 'Japan',
    'jackson':             'USA',
    'schecter':            'USA',
    'prs':                 'USA',
    'paul reed smith':     'USA',
    'orange amplification':'UK',
    'marshall':            'UK',
    'vox':                 'UK',
    'roland':              'Japan',
    'korg':                'Japan',
    'boss pedals':         'Japan',
    'zoom':                'Japan',
    'line 6':              'USA',
    'mxr':                 'USA',
    'electro-harmonix':    'USA',
    'tc electronic':       'Denmark',
    'strymon':             'USA',
    'behringer':           'China',
    'alesis':              'USA',
    'akai':                'USA',
    'native instruments':  'Germany',
    'focusrite':           'UK',
    'ssl':                 'UK',
    'audient':             'UK',
    'presonus':            'USA',
    'motu':                'USA',

    # ── Food & Grocery ────────────────────────────────────────────────────
    'heinz':               'USA',
    'kellogg\'s':          'USA',
    'nestle':              'Switzerland',
    'unilever':            'Netherlands',
    'procter & gamble':    'USA',
    'coca-cola':           'USA',
    'pepsi':               'USA',
    'mondelez':            'USA',
    'cadbury':             'UK',
    'rowntrees':           'UK',
    'haribo':              'Germany',
    'ferrero':             'Italy',
    'lindt':               'Switzerland',
    'green & blacks':      'UK',
    'hotel chocolat':      'UK',
    'baxters':             'UK',
    'schwartz':            'USA',
    'lea & perrins':       'UK',
    'tabasco':             'USA',
    'nando\'s':            'South Africa',
    'encona':              'UK',
    'nando':               'South Africa',
    'meridian':            'UK',
    'whole earth':         'UK',
    'rowse':               'UK',
    'filippo berio':       'Italy',
    'napolina':            'Italy',
    'cirio':               'Italy',
    'mutti':               'Italy',

    # ── Office Furniture & Chairs ─────────────────────────────────────────
    'herman miller chairs':'USA',
    'humanscale chairs':   'USA',
    'steelcase':           'USA',
    'haworth':             'USA',
    'kinnarps':            'Sweden',
    'flokk':               'Norway',
    'hag':                 'Norway',
    'girsberger':          'Switzerland',
    'sedia':               'Italy',
    'interstuhl':          'Germany',
    'wilkhahn':            'Germany',
    'sedus':               'Germany',
    'könig & neurath':     'Germany',
    'aeris':               'Germany',
    'hm office':           'China',
    'flexispot':           'China',
    'uplift desk':         'USA',
    'jarvis':              'USA',
    'autonomous':          'Vietnam',
    'omnidesk':            'Singapore',
    'secretlab':           'Singapore',
    'noblechairs':         'Germany',
    'dx racer':            'China',
    'dxracer':             'China',
    'akracing':            'China',
    'andaseatz':           'China',
    'gt omega':            'UK',
    'brazen gaming':       'UK',
    'x rocker':            'China',
    'respawn':             'USA',

    # ── Camping & Hiking ──────────────────────────────────────────────────
    'vango':               'UK',
    'outwell':             'Denmark',
    'robens':              'Denmark',
    'coleman':             'USA',
    'easy camp':           'Denmark',
    'hi-gear':             'UK',
    'gelert':              'UK',
    'eurohike':            'UK',
    'terra nova':          'UK',
    'wild country':        'UK',
    'rab':                 'UK',
    'montane':             'UK',
    'mountain equipment':  'UK',
    'alpkit':              'UK',
    'snugpak':             'UK',
    'criterion':           'UK',
    'western mountaineering': 'USA',
    'sea to summit':       'Australia',
    'leki':                'Germany',
    'black diamond poles': 'USA',
    'komperdell':          'Austria',
    'trekmates':           'UK',
    'lifeventure':         'UK',
    'highlander':          'UK',
    'terra peak':          'Germany',
    'salewa':              'Italy',
    'icebreaker':          'New Zealand',
    'smartwool':           'USA',
    'darn tough':          'USA',
    'stance socks':        'USA',
    'bridgedale':          'UK',

    # ── Cycling ────────────────────────────────────────────────────────────
    'trek':                'USA',
    'specialized':         'USA',
    'giant':               'Taiwan',
    'cannondale':          'USA',
    'scott bikes':         'Switzerland',
    'cervelo':             'Canada',
    'pinarello':           'Italy',
    'colnago':             'Italy',
    'de rosa':             'Italy',
    'bianchi':             'Italy',
    'orbea':               'Spain',
    'focus bikes':         'Germany',
    'cube bikes':          'Germany',
    'merida':              'Taiwan',
    'kona':                'USA',
    'marin bikes':         'USA',
    'voodoo':              'UK',
    'carrera':             'UK',
    'raleigh':             'UK',
    'ribble':              'UK',
    'boardman':            'UK',
    'vitus':               'UK',
    'forme':               'UK',
    'pinnacle':            'UK',
    'carrera bikes':       'UK',
    'shimano':             'Japan',
    'sram':                'USA',
    'campagnolo':          'Italy',
    'mavic':               'France',
    'fulcrum':             'Italy',
    'garmin cycling':      'Taiwan',
    'wahoo':               'USA',
    'polar cycling':       'Finland',
    'topeak':              'Taiwan',
    'lezyne':              'Taiwan',
    'knog':                'Australia',
    'exposure lights':     'UK',
    'lezyne lights':       'Taiwan',
    'cycliq':              'Australia',
    'ortlieb':             'Germany',
    'altura':              'UK',
    'castelli':            'Italy',
    'rapha':               'UK',
    'assos':               'Switzerland',
    'endura':              'UK',
    'gore cycling':        'Germany',
    'dhb':                 'UK',

    # ── Swimming & Water Sports ───────────────────────────────────────────
    'speedo':              'UK',
    'arena swim':          'France',
    'tyr':                 'USA',
    'zoggs':               'UK',
    'aqua sphere':         'Italy',
    'mad wave':            'Russia',
    'huub':                'UK',
    'sailfish':            'Germany',
    'orca':                'New Zealand',
    'blueseventy':         'USA',
    'roka':                'USA',
    'cressi':              'Italy',
    'mares':               'Italy',
    'scubapro':            'USA',
    'aqualung':            'France',
    'bcd':                 'USA',
    'mistral':             'Germany',
    'jobe':                'Netherlands',
    'aquaglide':           'USA',
    'sevylor':             'USA',
    'intex':               'China',
    'bestway':             'China',

    # ── Photography ───────────────────────────────────────────────────────
    'canon':               'Japan',
    'nikon':               'Japan',
    'sony camera':         'Japan',
    'fujifilm':            'Japan',
    'olympus':             'Japan',
    'pentax':              'Japan',
    'leica':               'Germany',
    'hasselblad':          'Sweden',
    'phase one':           'Denmark',
    'mamiya':              'Japan',
    'sigma':               'Japan',
    'tamron':              'Japan',
    'tokina':              'Japan',
    'samyang':             'South Korea',
    'zeiss':               'Germany',
    'voigtlander':         'Germany',
    'gopro':               'USA',
    'dji':                 'China',
    'insta360':            'China',
    'manfrotto':           'Italy',
    'gitzo':               'Italy',
    'joby':                'USA',
    'peak design camera':  'USA',
    'think tank':          'USA',
    'lowepro':             'USA',
    'f-stop':              'USA',
    'billingham':          'UK',
    'tenba':               'USA',
    'hoya':                'Japan',
    'b+w filters':         'Germany',
    'cokin':               'France',
    'lee filters':         'UK',

    # ── Books / Media ─────────────────────────────────────────────────────
    'penguin':             'UK',
    'bloomsbury':          'UK',
    'hodder':              'UK',
    'pan macmillan':       'UK',
    'harpercollins':       'USA',
    'simon & schuster':    'USA',
    'random house':        'USA',
    'oxford university press': 'UK',
    'cambridge university press': 'UK',
    'dk books':            'UK',
    'usborne':             'UK',
    'ladybird':            'UK',
    'oxford owl':          'UK',

    # ── Cleaning & Laundry ────────────────────────────────────────────────
    'fairy':               'USA',
    'ariel':               'USA',
    'persil':              'Netherlands',
    'surf':                'Netherlands',
    'bold':                'USA',
    'daz':                 'USA',
    'ecover':              'Belgium',
    'method':              'USA',
    'bio-d':               'UK',
    'smol':                'UK',
    'eco egg':             'UK',
    'flash':               'USA',
    'mr muscle':           'USA',
    'cillit bang':         'UK',
    'harpic':              'UK',
    'domestos':            'Netherlands',
    'zoflora':             'UK',
    'jeyes':               'UK',
    'pine o cleen':        'Australia',
    'elbow grease':        'UK',
    'astonish':            'UK',
    'stardrops':           'UK',
    'pink stuff':          'UK',
    'scrub daddy':         'USA',
    'vileda':              'Germany',
    'spontex':             'France',
    'e-cloth':             'UK',
    'minky':               'UK',
    'addis':               'UK',
    'brabantia':           'Netherlands',
    'joseph joseph laundry': 'UK',
    'leifheit':            'Germany',
}


# ---------------------------------------------------------------------------
# Amazon UK category search terms
# ---------------------------------------------------------------------------

AMAZON_SEARCH_CATEGORIES = [
    ('glass table', 'Furniture'),
    ('dining table', 'Furniture'),
    ('coffee table', 'Furniture'),
    ('office desk', 'Furniture'),
    ('kitchen knives', 'Kitchen'),
    ('chef knife', 'Kitchen'),
    ('table lamp', 'Lighting'),
    ('led light bulb', 'Lighting'),
    ('floor lamp', 'Lighting'),
    ('water bottle', 'Drinkware'),
    ('insulated bottle', 'Drinkware'),
    ('electric kettle', 'Appliances'),
    ('toaster', 'Appliances'),
    ('mens watch', 'Watches'),
    ('womens watch', 'Watches'),
    ('smartwatch', 'Electronics'),
    ('bluetooth headphones', 'Electronics'),
    ('phone case', 'Electronics'),
    ('yoga mat', 'Sports'),
    ('running shoes', 'Sports'),
    ('notebook journal', 'Stationery'),
    ('dog food', 'Pet'),
    ('cat food', 'Pet'),
    ('garden trowel', 'Garden'),
    ('plant pot', 'Garden'),
]


def load_brand_json(path: str) -> dict:
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_brand_json(path: str, data: dict) -> None:
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"✅ Saved {len(data) - 1} brands to {path}")


def add_curated_brands(data: dict) -> int:
    """Add brands from CURATED_BRANDS. Returns number of new entries added."""
    added = 0
    for brand, country in CURATED_BRANDS.items():
        key = brand.lower().strip()
        if key not in data:
            data[key] = {'origin': {'country': country}}
            added += 1
    return added


def scrape_amazon_search_brands(search_term: str) -> list:
    """
    Fetch the first page of Amazon UK results for search_term and extract
    brand names from product listings.  Returns list of (brand, asin) tuples.
    """
    try:
        import requests
        from bs4 import BeautifulSoup
    except ImportError:
        print("⚠️  requests/beautifulsoup4 not available — skipping live scrape")
        return []

    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/120.0.0.0 Safari/537.36'
        ),
        'Accept-Language': 'en-GB,en;q=0.9',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Encoding': 'gzip, deflate, br',
        'DNT': '1',
        'Connection': 'keep-alive',
    }

    url = f'https://www.amazon.co.uk/s?k={search_term.replace(" ", "+")}'
    print(f"  🔍 Scraping: {url}")

    try:
        resp = requests.get(url, headers=headers, timeout=10)
        if resp.status_code != 200:
            print(f"  ⚠️  HTTP {resp.status_code} for '{search_term}'")
            return []

        soup = BeautifulSoup(resp.text, 'html.parser')

        brands = []

        # Selector 1: sponsored/organic product cards → span with data-asin
        for card in soup.select('[data-asin]'):
            asin = card.get('data-asin', '').strip()
            if not asin:
                continue

            # Brand from "by <brand>" span
            by_brand = card.select_one('.a-row.a-size-base.a-color-secondary span')
            if by_brand:
                text = by_brand.get_text(strip=True)
                m = re.match(r'^(?:by|brand:|visit the)\s+(.+?)(?:\s+store)?$', text, re.I)
                if m:
                    brands.append((m.group(1).strip(), asin))
                    continue

            # Brand from product title h2 aria-label or data attributes
            title_el = card.select_one('h2 span')
            if title_el:
                title_text = title_el.get_text(strip=True)
                # First word of title is often the brand
                first_word = title_text.split()[0] if title_text else None
                if first_word and len(first_word) > 2:
                    brands.append((first_word, asin))

        return brands

    except Exception as e:
        print(f"  ⚠️  Scrape failed for '{search_term}': {e}")
        return []


def infer_country_from_brand_name(brand: str) -> str | None:
    """
    Very rough heuristic: return a likely manufacturing country based on
    common naming patterns.  Returns None when the brand is unrecognised.
    """
    b = brand.lower()
    japanese = ['ao', 'yama', 'moto', 'kawa', 'tani', 'shiro', 'haru', 'nori', 'seki']
    chinese_suffix = ['tech', 'led', 'smart', 'plus', 'pro', 'max', 'x', 'go']
    german = ['mann', 'haus', 'berg', 'bach', 'feld']

    for tok in japanese:
        if tok in b:
            return 'Japan'
    if any(b.endswith(s) for s in german):
        return 'Germany'
    # Default for unknown brands from Amazon UK → likely China-manufactured
    return 'China'


def run(live_scrape: bool = False):
    print(f"📂 Loading {BRAND_JSON_PATH}")
    data = load_brand_json(BRAND_JSON_PATH)
    existing_before = len(data) - 1   # subtract _metadata

    # 1. Add curated list
    curated_added = add_curated_brands(data)
    print(f"✅ Added {curated_added} curated brands ({existing_before + curated_added} total)")

    # 2. Optionally scrape Amazon UK
    scrape_added = 0
    if live_scrape:
        print("\n🌐 Starting live Amazon UK scrape…")
        for search_term, category in AMAZON_SEARCH_CATEGORIES:
            results = scrape_amazon_search_brands(search_term)
            for brand, asin in results:
                key = brand.lower().strip()
                # Skip very short / numeric / already present
                if len(key) < 3 or key.isdigit() or key in data:
                    continue
                guessed = infer_country_from_brand_name(brand)
                if guessed:
                    data[key] = {'origin': {'country': guessed}}
                    scrape_added += 1
                    print(f"    + {brand!r} → {guessed} (category: {category})")
            # Polite delay between search pages
            time.sleep(random.uniform(2.5, 4.5))

        print(f"\n✅ Scraped {scrape_added} additional brands")

    # 3. Update metadata
    if '_metadata' in data:
        data['_metadata']['total_brands'] = str(len(data) - 1)
        data['_metadata']['last_updated'] = '2026-04-03'

    save_brand_json(BRAND_JSON_PATH, data)
    print(f"\n📊 Summary: {existing_before} → {len(data) - 1} brands "
          f"(+{curated_added} curated, +{scrape_added} scraped)")


if __name__ == '__main__':
    live = '--scrape' in sys.argv
    run(live_scrape=live)
